
import esbuild from "esbuild";
import builtins from "builtin-modules";
import process from "process";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Context for Obsidian Plugin (main.ts -> main.js)
const pluginContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  }
});

// Context for Web Preview (index.tsx -> web.js)
// We treat react/react-dom as external because we load them via ESM.sh in index.html
const webContext = await esbuild.context({
  entryPoints: ["index.tsx"],
  bundle: true,
  external: ["react", "react-dom", "react-dom/client", "@google/genai", "lucide-react", "html-to-image", "obsidian"],
  format: "esm",
  target: "es2020",
  logLevel: "info",
  sourcemap: true,
  outfile: "web.js",
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  }
});

if (prod) {
	await Promise.all([pluginContext.rebuild(), webContext.rebuild()]);
    // Rename main.css (generated from importing css in main.ts/App.tsx) to styles.css for Obsidian
    if (fs.existsSync('main.css')) {
        fs.renameSync('main.css', 'styles.css');
    }
	process.exit(0);
} else {
	await Promise.all([pluginContext.watch(), webContext.watch()]);
}
